### ISSUE TITLE
Crear texto introductorio sobre el cache para la home

### ISSUE THREAD

**Issue by diegosalazarCO** [izel-networks/refresca-tu-cache#5]
Tomar como referencia el texto disponible en [refreshyourcache.com](http://refreshyourcache.com).

**Comment by codelando** [comment]
Texto introductorio. Se puede modificar si queremos que el sitio tenga un tono más "serio".

> ¿Por qué estoy en este sitio y qué es esto del cache?
> 
> En la mayor parte de los casos cuando visitas un sitio por primera vez, parte de sus archivos son guardados o "cacheados" en una carpeta de tu disco rígido. Cuando accedes al mismo sitio por segunda vez, el navegador verifica si los archivos del sitio ya se han descargado anteriormente y si es así los muestra desde el cache local sin necesidad de descargalos de internet. Esto ahorra tiempo y ancho de banda haciendo que la navegación sea efectivamente más rápida.
> 
> En algunos casos este cache puede generar problemas, especialmente si existen archivos más recientes en el sitio que estamos visitando y nuestro navegador esté empeñado en mostrarnos la versión anterior que está guardada en el cache. En esos casos no bastará con darle al botón de refrescar y deberemos borrar el cache de nuestro navegador manualmente. ¡Pero no temas! Aquí encontrarás sencillas explicaciones para cada uno de los principales navegadores.
